// <auto-generated />
namespace DbConection.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class first_migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(first_migration));
        
        string IMigrationMetadata.Id
        {
            get { return "201911070042382_first_migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
